### ISSUE TITLE
Output becomes longer in each iteration

### ISSUE THREAD

**Issue by buhtzz** [klieret/RandomFileTree#30]
The output of `iterative_gaussian_tree()` becomes longer/bigger with each iteration without modifying the arguments.

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import randomfiletree
>>> for _ in range(5):
...     result = randomfiletree.core.iterative_gaussian_tree('~/treetest', nfiles=1)
...     print(len(str(result)))
...

38
73
196
264
592
>>>
>>> for _ in range(20):
...     result = randomfiletree.core.iterative_gaussian_tree('~/treetest', nfiles=1)
...     print(len(str(result)))
...
1037
1813
3706
6235
11087
21754
36542
65439
110768
191137
336480
576835
1011733
1767550
3070870
5379120
9349156
16151620
28104107
48539849
```

**Comment by klieret** [comment]
Hi, thanks for opening this. 

However, this is expected, because the directory is not wiped after every call. The randomfiletree creator will then walk down the directory and there's some configurable probabilities/expectation values of creating new files or folders. So if there's already more things there, then more things will also be created. 

Does that make sense?

Closing this for now, feel free to comment with questions :)
